@ByteArray_HostAddress = http://localhost:5247

GET {{ByteArray_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{ByteArray_HostAddress}}/weatherforecast/upload
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
{
  "Data": "SGVqIG1lZCBkaWc=",
  "FileName": "Filename",
  "Description": "Description",
}
